# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#______________________________________________________________________________

import numpy as np


def fibo():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b 
        return a, b

l = []

while l.sum() < 4*10**6:
	 l.append(fibo())


print(sum([x for x in l if x % 2 == 0]))
	